/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author admin
 */
public class Transaksi extends javax.swing.JFrame {
    public Statement st;
    Connection cn = Koneksi.getKoneksi();
            
    private DefaultTableModel model;
    /**
     * Creates new form Transaksii
     */
    public Transaksi() {
        initComponents();
        
        model =new DefaultTableModel();
        jTable1.setModel(model);
        model.addColumn("kode buku");
        model.addColumn("judul");
        model.addColumn("harga");
        model.addColumn("jumlah_beli");
        model.addColumn("sub_total");
        
        Date date = new Date();
        tampilpilih();
        kodeotomatis();
        Stok.hide();
                loadData();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jumlah_beli = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        judul = new javax.swing.JTextField();
        kode_buku = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        subtotal = new javax.swing.JTextField();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        total_bayar = new javax.swing.JTextField();
        bayar_Cash = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bTambah2 = new javax.swing.JButton();
        No_transaksi = new javax.swing.JTextField();
        bTambah3 = new javax.swing.JButton();
        print = new javax.swing.JTextField();
        Stok = new javax.swing.JTextField();
        total_bayar1 = new javax.swing.JTextField();
        total_bayar2 = new javax.swing.JTextField();
        total_bayar3 = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBox.shadow"));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Transaksi");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("No.Transaksi");

        jumlah_beli.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jumlah_beli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jumlah_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_beliActionPerformed(evt);
            }
        });
        jumlah_beli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jumlah_beliKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlah_beliKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlah_beliKeyTyped(evt);
            }
        });

        harga.setEditable(false);
        harga.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        harga.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        judul.setEditable(false);
        judul.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        judul.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulActionPerformed(evt);
            }
        });

        kode_buku.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        kode_buku.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Barang" }));
        kode_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_bukuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Kode");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Jumlah Beli");

        subtotal.setEditable(false);
        subtotal.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        subtotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });

        bTambah.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bTambah.setText("Tambah Item");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bHapus.setText("Batal");
        bHapus.setEnabled(false);
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Judul");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Subtotal");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        jLabel9.setText("*Tekan Enter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jumlah_beli, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kode_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlah_beli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Buku", "Judul", "Harga", "Jumlah", "Subtotal"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        total_bayar.setEditable(false);
        total_bayar.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        total_bayar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        total_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bayarActionPerformed(evt);
            }
        });

        bayar_Cash.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        bayar_Cash.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        bayar_Cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayar_CashActionPerformed(evt);
            }
        });
        bayar_Cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bayar_CashKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayar_CashKeyTyped(evt);
            }
        });

        kembalian.setEditable(false);
        kembalian.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        kembalian.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Rp.");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        bTambah2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bTambah2.setText("Simpan");
        bTambah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah2ActionPerformed(evt);
            }
        });

        No_transaksi.setEditable(false);
        No_transaksi.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        No_transaksi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        No_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                No_transaksiActionPerformed(evt);
            }
        });

        bTambah3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        bTambah3.setText("Print");
        bTambah3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambah3ActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        print.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        print.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                printKeyTyped(evt);
            }
        });

        total_bayar1.setEditable(false);
        total_bayar1.setBackground(new java.awt.Color(204, 204, 204));
        total_bayar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        total_bayar1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_bayar1.setText("  Total  ");
        total_bayar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        total_bayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bayar1ActionPerformed(evt);
            }
        });

        total_bayar2.setEditable(false);
        total_bayar2.setBackground(new java.awt.Color(204, 204, 204));
        total_bayar2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        total_bayar2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_bayar2.setText("Bayar  ");
        total_bayar2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        total_bayar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bayar2ActionPerformed(evt);
            }
        });

        total_bayar3.setEditable(false);
        total_bayar3.setBackground(new java.awt.Color(204, 204, 204));
        total_bayar3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        total_bayar3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        total_bayar3.setText("Kembalian  ");
        total_bayar3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        total_bayar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bayar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(No_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(bTambah3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(448, 448, 448))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(total_bayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bTambah2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(total_bayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bayar_Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(total_bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(No_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_bayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bayar_Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_bayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_bayar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah2)
                    .addComponent(bTambah3))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlah_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_beliActionPerformed

    private void jumlah_beliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_beliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jumlah_beli.getText().equals("") || harga.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "TK. Sinar Abadi", JOptionPane.INFORMATION_MESSAGE);
            }else{
                String a = jumlah_beli.getText();
                int aa = Integer.parseInt(a);
                String b = Stok.getText();
                int bb = Integer.parseInt(b);
                if(aa > bb){
                    JOptionPane.showMessageDialog(null, "Jumlah beli melebihi Stok yang Ada " + bb, "TK. Abadi Jaya", JOptionPane.INFORMATION_MESSAGE);
                    jumlah_beli.setText("");
                }else{
                    int angka1,angka2,jumlah;
                    angka1 = Integer.parseInt(harga.getText().toString());
                    angka2 = Integer.parseInt(jumlah_beli.getText().toString());
                    jumlah = angka1 * angka2;
                    subtotal.setText(Integer.toString(jumlah));
                    loadData();
                }
            }
        }
    }//GEN-LAST:event_jumlah_beliKeyPressed
        private void tampilpilih() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT kd_buku FROM buku WHERE stok !='0'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                kode_buku.addItem(r.getString("kd_buku"));
            }
            r.last();
            int jumlahdata = r.getRow();
            r.first();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
    }

        
            public void FilterHuruf(KeyEvent a){
       if(Character.isDigit(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan huruf saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
    }
    public void FilterAngka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
    }
    private void kodeotomatis() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM head_transaksi ORDER by no_transaksi desc";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String nofak = r.getString("no_transaksi").substring(2);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";
                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

                No_transaksi.setText("TR" + Nol + AN);
            } else {
                No_transaksi.setText("TR0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
     
    }

    public final void loadData(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
            Connection c= Koneksi.getKoneksi();
            Statement s= c.createStatement();
            String sql="Select * from detail_transaksi, buku WHERE detail_transaksi.kd_buku = buku.kd_buku AND detail_transaksi.no_transaksi='"+ No_transaksi.getText()+"'";
            ResultSet r=s.executeQuery(sql);
            while(r.next()){
                Object[]o=new Object[5];
                o[0]=r.getString("kd_buku");
                o[1]=r.getString("judul");
                o[2]=r.getString("harga");
                o[3]=r.getString("jumlah_beli");
                o[4]=r.getString("subtotal");
                model.addRow(o);
            }
            r.close();
            s.close();  
            //ShowData();  
        }catch(SQLException e){      
            System.out.println("Terjadi Kesalahan");  
        }
   //menjumlahkan isi colom ke 4 dalam tabel
        int totalhargabayar = 0;
        int ia;
        for (ia =0; ia< jTable1.getRowCount(); ia++){
            int amount = Integer.parseInt((String)jTable1.getValueAt(ia, 4));
            totalhargabayar += amount;
        }
        total_bayar.setText(""+totalhargabayar);
        jTextField1.setText(""+totalhargabayar);
    }

    private void jumlah_beliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_beliKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jumlah_beliKeyReleased

    private void jumlah_beliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlah_beliKeyTyped

        FilterAngka(evt);
    }//GEN-LAST:event_jumlah_beliKeyTyped

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulActionPerformed

    private void kode_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_bukuActionPerformed
        // TODO add your handling code here:
        if (kode_buku.getSelectedItem().equals("pilih barang")){
            judul.setText("");
            harga.setText("");
        }else{
            try {
                Connection c = Koneksi.getKoneksi();
                Statement s = c.createStatement();

                String sql = "SELECT judul, harga, stok FROM buku WHERE kd_buku ='" + kode_buku.getSelectedItem() + "'";
                ResultSet r = s.executeQuery(sql);

                while (r.next()) {
                    judul.setText(r.getString("judul"));
                    harga.setText(r.getString("harga"));
                    Stok.setText (r.getString("stok"));
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_kode_bukuActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotalActionPerformed

    
    public void ShowSisa(){
   
        try {
        Connection c=Koneksi.getKoneksi();
        String sql="Select * from  buku WHERE kd_buku ='"+ kode_buku.getSelectedItem()+"'"; 
        Statement st = Koneksi.getKoneksi().createStatement();
        ResultSet rs = st.executeQuery(sql);
        while(rs.next()){
            Stok.setText(rs.getString("stok"));      
        }
        rs.close(); 
        st.close();}
        catch (Exception e) {
            System.out.println(e.getMessage());
        }
 } 
    
    public void UpdateStock(){
    int x, y, z;
    x = Integer.parseInt(Stok.getText());
    y = Integer.parseInt(jumlah_beli.getText());
    z = x-y;
    
    String kdbk= (String) kode_buku.getSelectedItem();
     try{
       Connection c= Koneksi.getKoneksi();  
       String sql ="UPDATE buku set stok=? WHERE kd_buku=?";  
       PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);  
           p.setInt(1,z);
           p.setString(2,kdbk);//yang kode atau id letakkan di nomor terakhir  
           p.executeUpdate();  
           p.close();  
     }catch(SQLException e){  
       System.out.println("Terjadi Kesalahan");  
     }finally{   
       //JOptionPane.showMessageDialog(this,"Stock barang telah di update Diubah");  
     }
}

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        if(kode_buku.getSelectedItem().equals("") || judul.getText().equals("") || harga.getText().equals("")|| jumlah_beli.getText().equals("")|| subtotal.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "TK. Sinar Abadi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            Date HariSekarang = new Date( );
            SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd hh:mm:ss");
            String notrans = No_transaksi.getText();
            String kdbk = (String) kode_buku.getSelectedItem();
            String hrg = harga.getText();
            String jmlh = jumlah_beli.getText();
            String sbtotal = subtotal.getText();
            String DateTime = ft.format(HariSekarang);
            try{
                Connection c = Koneksi.getKoneksi();
                String sql="Insert into detail_transaksi values (?,?,?,?,?,?)";
                PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);
                p.setString(1,notrans);
                p.setString(2,kdbk);
                p.setString(3,hrg);
                p.setString(4,jmlh);
                p.setString(5,sbtotal);
                p.setString(6,DateTime);
                p.executeUpdate();
                p.close();
            }catch(SQLException e){
                System.out.println(e);
            }finally{
                //loadData();
                JOptionPane.showMessageDialog(this,"Data Telah Tersimpan");
                UpdateStock();
                ShowSisa();
                loadData();
                kode_buku.setSelectedItem("");
                judul.setText("");
                harga.setText("");
                jumlah_beli.setText("");
                subtotal.setText("");
                bayar_Cash.setText("");
                kembalian.setText("");
            }
        }
    }//GEN-LAST:event_bTambahActionPerformed
    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
//        //Proses mengahapus data dari tabel detail
        int x, y, z;
        x = Integer.parseInt(Stok.getText());
        y = Integer.parseInt(jumlah_beli.getText());
        z = x+y;
        String kdb= (String) kode_buku.getSelectedItem();
        try{
            Connection c= Koneksi.getKoneksi();
            String sql ="UPDATE buku set stok=? WHERE kd_buku='"+ kdb  +"'";
            PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);
            p.setInt(1,z);
//            p.setString(2,kdb);//yang kode atau id letakkan di nomor terakhir  
            p.executeUpdate();
            p.close();
        }catch(SQLException e){
            System.out.println("Terjadi Kesalahan");
        }finally{
//JOptionPane.showMessageDialog(this,"Stock barang telah di update Diubah");  
        }
        try {
            Connection c= Koneksi.getKoneksi();
            String sql="DELETE From detail_transaksi WHERE no_transaksi='"+ No_transaksi.getText()+"' AND kd_buku='"+ kode_buku.getSelectedItem() +"'";
            PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);
            p.executeUpdate();
            p.close();
        }catch(SQLException e){
            System.out.println("Terjadi Kesalahan");
        }finally{
            loadData();
            bTambah.setEnabled(true);
            bHapus.setEnabled(false);
            jumlah_beli.setEnabled(true);
            JOptionPane.showMessageDialog(this,"Sukses Hapus Data...");
            kode_buku.setSelectedItem("");
            judul.setText("");
            harga.setText("");
            jumlah_beli.setText("");
            subtotal.setText("");
            kembalian.setText("");
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void total_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_bayarActionPerformed

    private void bayar_CashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayar_CashActionPerformed

    }//GEN-LAST:event_bayar_CashActionPerformed

    private void bayar_CashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayar_CashKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (total_bayar.getText().equals("") || bayar_Cash.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "TK. Abadi Jaya", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int a,b,c;
                a = Integer.parseInt(total_bayar.getText().toString());
                b = Integer.parseInt(bayar_Cash.getText().toString());
                c = b - a;
                kembalian.setText(Integer.toString(c));
            }
        }
    }//GEN-LAST:event_bayar_CashKeyPressed

    private void bayar_CashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayar_CashKeyTyped
        // TODO add your handling code here:
        FilterAngka(evt);
    }//GEN-LAST:event_bayar_CashKeyTyped

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void bTambah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah2ActionPerformed
        if(total_bayar.getText().equals("") || bayar_Cash.getText().equals("")|| kembalian.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Data", "TK. Sinar Abadi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            int ab = Integer.parseInt(String.valueOf(kembalian.getText()));
            if(ab < 0){
                JOptionPane.showMessageDialog(null, "Uang anda kurang", "Elektronik Berkah", JOptionPane.INFORMATION_MESSAGE);
                bayar_Cash.setText("");
                kembalian.setText("");
            }else{
                Date HariSekarang = new Date( );
                SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd hh:mm:ss");
                String notrans = No_transaksi.getText();
                String tot = total_bayar.getText();
                String byr = bayar_Cash.getText();
                String kmbl = kembalian.getText();
                String DateTime = ft.format(HariSekarang);
                try{
                    Connection c = Koneksi.getKoneksi();
                    String sql="Insert into head_transaksi values (?,?,?,?,?)";
                    PreparedStatement p=(PreparedStatement)c.prepareStatement(sql);
                    p.setString(1,notrans);
                    p.setString(2,DateTime);
                    p.setString(3,tot);
                    p.setString(4,byr);
                    p.setString(5,kmbl);
                    p.executeUpdate();
                    p.close();
                }catch(SQLException e){
                    System.out.println(e);
                }finally{
                //loadData();
                    JOptionPane.showMessageDialog(this,"Data Telah Tersimpan");
                    kodeotomatis();
                    ShowSisa();
                    loadData();            
                    jTextField1.setText("");            
                    kode_buku.setSelectedItem("");            
                    judul.setText("");                
                    harga.setText("");                
                    jumlah_beli.setText("");
                    subtotal.setText("");                
                    bayar_Cash.setText("");                
                    kembalian.setText("");        
                }
            }
        }    
    }//GEN-LAST:event_bTambah2ActionPerformed

    private void No_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_No_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_No_transaksiActionPerformed

    private void bTambah3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambah3ActionPerformed
        // TODO add your handling code here:
        JasperReport jasRep;
        JasperPrint jasPri;
        Map param = new HashMap();
        JasperDesign jasDes;
        try {
            
            File file = new File("src\\projek\\rStruk.jrxml");
            jasDes = JRXmlLoader.load(file);
            //param.clear();
            param.put("notrans",print.getText());
            jasRep = JasperCompileManager.compileReport(jasDes);
            jasPri = JasperFillManager.fillReport(jasRep, param,    Koneksi.getKoneksi());
            JasperViewer.viewReport(jasPri, false);
        } catch (Exception e) {
 
        }
    }//GEN-LAST:event_bTambah3ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printActionPerformed

    private void printKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_printKeyPressed

    private void printKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_printKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
//        // TODO add your handling code here:
//        Cari_Kode();
//        ShowSisa();        
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }
        String kdbk = (String) model.getValueAt(i, 0);
        kode_buku.setSelectedItem(kdbk);

        String nmbrg = (String) model.getValueAt(i, 1);
        judul.setText(nmbrg);

        String hrg = (String) model.getValueAt(i, 2);
        harga.setText(hrg);

        String jml = (String) model.getValueAt(i, 3);
        jumlah_beli.setText(jml);

        String sbttl = (String) model.getValueAt(i, 4);
        subtotal.setText(sbttl);
        
        ShowSisa();
        bHapus.setEnabled(true);
        bTambah.setEnabled(false);
        jumlah_beli.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void total_bayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bayar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_bayar1ActionPerformed

    private void total_bayar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bayar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_bayar2ActionPerformed

    private void total_bayar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bayar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_bayar3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField No_transaksi;
    private javax.swing.JTextField Stok;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bTambah2;
    private javax.swing.JButton bTambah3;
    private javax.swing.JTextField bayar_Cash;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField jumlah_beli;
    private javax.swing.JTextField kembalian;
    private javax.swing.JComboBox kode_buku;
    private javax.swing.JTextField print;
    private javax.swing.JTextField subtotal;
    private javax.swing.JTextField total_bayar;
    private javax.swing.JTextField total_bayar1;
    private javax.swing.JTextField total_bayar2;
    private javax.swing.JTextField total_bayar3;
    // End of variables declaration//GEN-END:variables
}
